### PR TITLE
Modify git source install path

### PR DESCRIPTION
**Pull request by VinnyQ**
# What

Modify source install path for graphite-api
# Why

Reforked official graphite-api version 1.1.3 and added events support for grafana (tagged to 1.1.3-rax.1).

### CODE REVIEW

**Comment by VinnyQ** [comment]
@ChandraAddala please review!

**Comment by usnavi** [comment]
lgtm

**Comment by goru97** [comment]
👍

**Comment by ChandraAddala** [comment]
Looks good.

**Pull request merged**
