### PR TITLE
George/fix grafana

### PR DESCRIPTION
**Pull request by GeorgeJahad**
added shinta's commits to add grafana, plus a few fixes

### CODE REVIEW

**Review by izrik — COMMENTED** [review]
@GeorgeJahad Don't you need to update the `/etc/graphite-api.yaml` file to enable statsd? See [here](https://github.com/rackerlabs/blueflood-graphite-finder/pull/12/files#diff-04c6e90faac2675aa89e2176d2eec7d8R29).

**Comment by GeorgeJahad** [comment]
@izrik it depends on which is more popular.  I wasn't sure so I didn't add it.  If you think I should, I will.

**Comment by izrik** [comment]
@GeorgeJahad No, that makes sense. lgtm +1

**Comment by GeorgeJahad** [comment]
thank you sir

**Pull request merged**
